name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
  confetti: ^0.5.5
  badges: ^1.2.0
  flutter_animation_progress_bar: ^2.0.0
  step_progress_indicator: ^0.2.5+8
  bordered_text: ^1.0.1
  package_info: ^2.0.0
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_messaging: ^10.0.0
  provider: ^5.0.0
  firebase_storage: ^8.1.3
  firebase_analytics: ^8.2.0
  image_picker: ^0.8.0+3
  multi_image_picker: ^4.7.14
  camera: ^0.8.1+3
  path: ^1.6.4
  path_provider: ^2.0.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  random_color: ^1.0.5
  shared_preferences: ^0.5.7
  connectivity: ^3.0.6
  open_settings: ^2.0.1
  fluttertoast: ^8.0.8
  connectivity_plus: ^1.0.6
  data_connection_checker: ^0.3.4
  flutter_widget_from_html_core: ^0.6.1
  pull_to_refresh: ^2.0.0

  
  # create signature pad
  syncfusion_flutter_signaturepad: ^19.1.69-beta
  # generate pdf document
  syncfusion_flutter_pdf: ^19.1.69-beta

  open_file: ^3.2.1
  permission_handler: ^8.1.1
  auth_buttons: ^1.0.1+4

  sign_in_with_apple: ^3.0.0
  google_sign_in: ^5.0.4


  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1


  


flutter_native_splash:  
  image: assets/images/splash.png
  color: "#ffffff"
  android: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo-BussgeldPruefer-small.png

    - assets/images/alcohol.jpg
    - assets/images/distance.jpg
    - assets/images/parking.jpg
    - assets/images/phone.jpg
    - assets/images/redlight.jpg
    - assets/images/speed.jpg
    # - assets/images/splashxhdpi.png

    - assets/images/icons/fast-time.png
    - assets/images/icons/assignment.png
    - assets/images/icons/communication.png
    - assets/images/icons/innovation.png
    - assets/images/icons/right.png
    - assets/images/icons/driving-license.png
    - assets/images/icons/happy.png
    - assets/images/icons/sad.png
    - assets/images/icons/question.png
    - assets/images/icons/traffic-light-green.png
    - assets/images/icons/traffic-light-red.png
    - assets/images/icons/traffic-light-yellow.png
    - assets/images/icons/traffic-light.png
    - assets/images/icons/confetti.png
    - assets/images/icons/exclamation-mark.png

    - assets/loading.gif
    - assets/images/icons/send.png
    - assets/images/icons/hollow_send.png
    - assets/documents/vollmacht.jpg
    - assets/documents/vollmacht.pdf
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
